on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_BASE64_GZIP_TFVARS_JSON: ${{ secrets.BASE64_GZIP_TFVARS_JSON }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ap-northeast-1
      - run: echo $TF_VAR_BASE64_GZIP_TFVARS_JSON | base64 --decode | gzip -d > terraform.tfvars.json
      - run: terraform init
      - run: terraform apply -auto-approve
